################### Ukrainian navigation ####################

# main menu
[[main]]
name = "Прозорість та інформаційна відкритість"
url = "prozorist/"
weight = 1

[[main]]
name = "Протидія булінгу"
url = "anti-bullying/"
weight = 2

[[main]]
weight = 3
name = "Сторінки"
hasChildren = true

  [[main]]
  parent = "Сторінки"
  name = "Адміністрація"
  url = "administration/"

  [[main]]
  parent = "Сторінки"
  name = "Вчителі"
  url = "teacher/"

  [[main]]
  parent = "Сторінки"
  name = "Оголошення"
  url = "notice/"

  [[main]]
  parent = "Сторінки"
  name = "Події"
  url = "event/"


[[main]]
weight = 4
name = "Посилання"
hasChildren = true

    [[main]]
    parent = "Посилання"
    name = "Блог практичного психолога Юсиченко Анни Вікторівни"
    url = "https://925anna.blogspot.com/"

[[main]]
name = "Блог"
url = "blog/"
weight = 4

[[main]]
name = "Контакти"
url = "contact/"
weight = 5


# footer menu

[[footer]]
name = "Вчителі"
url = "teacher/"

[[footer]]
name = "Оголошення"
url = "notice/"

[[footer]]
name = "Події"
url = "event/"
