################### Ukrainian navigation ####################

# main menu
[[main]]
name = "Прозорість та інформаційна відкритість"
url = "prozorist/"
weight = 1

[[main]]
name = "Протидія булінгу"
url = "anti-bullying/"
weight = 2

[[main]]
weight = 3
name = "Оголошення"
url = "notice/"

[[main]]
weight = 4
name = "Події"
url = "event/"


[[main]]
weight = 6
name = "Посилання"
hasChildren = true

    [[main]]
    parent = "Посилання"
    name = "Блог практичного психолога Юсиченко Анни Вікторівни"
    url = "https://925anna.blogspot.com/"

[[main]]
name = "Блог"
url = "blog/"
weight = 5

[[main]]
name = "Контакти"
url = "contact/"
weight = 7


# footer menu

[[footer]]
name = "Вчителі"
url = "teacher/"

[[footer]]
name = "Оголошення"
url = "notice/"

[[footer]]
name = "Події"
url = "event/"
